### ISSUE TITLE
specific path

### ISSUE THREAD

**Issue by lunalovegood600** [Googolxx/STF#10]
Hi !
Thank you for the great work ! could you please give me the specific path，e.g. the specific path of the evaluate command ：-r reconstruction path  -p path of  checkpoint？thank u very much！

**Comment by lunalovegood600** [comment]
thanks for your reply，I use the command "python downloader_openimages.py"to download the dataset "openimages" in the folder STF. Then I use the command"CUDA_VISIBLE_DEVICES=0 python -m compressai.utils.eval_model -d /openimages/test/data/ -r reconstruction -a cnn -p ckpt --cuda",but why there is an error "No such file or dictionary:'/openimages/test/data/'" ? Is there any fault in my path of the dataset？Or could u  please give me the specific path of the datasets？I would really appreciate it if you could give me some answers！

**Comment by Googolxx** [comment]
Using “openimages/test/data/” instead of "/openimages/test/data/"

**Comment by lunalovegood600** [comment]
thanks a lot！By the way，could u please tell me where can I download checkpoint？ The checkpoint  file is the cnn_xxxx_best.pth ?Please forgive me if I'm getting this wrong.

**Comment by Googolxx** [comment]
Yes, the checkpoint file is "cnn_xxxx_best.pth" , Download links have been provided in "Readme.md".  For example, [cnn_0035_best.pth](https://drive.google.com/file/d/1VUV6_Ws-3X6VZDKkfOVPQel8nr7ecut9/view)
