### ISSUE TITLE
Pre-trained model weights

### ISSUE THREAD

**Issue by duanzhiihao** [Googolxx/STF#11]
Hi,

First of all thanks for you great work!
I wonder if it is possible to release **all** pre-trained model weights (right now I think there are only two available) that correspond to your results in the paper.
I would like to evaluate the STF model on various dataset (other than Kodak) so that I'm able to compare it with my own research.

Thanks. Any feedback is appreciated.

**Comment by Googolxx** [comment]
Hi,

The code was reorganize, so I'm unable to provide all pretrained weights right away. Sorry for that. 
I will train the models from scratch to get remaining pretrained weights, during this month when additional GPU resources are available.
Hope it helps.

**Comment by duanzhiihao** [comment]
That would be great, thanks!
I look forward to your good news.

**Comment by duanzhiihao** [comment]
Hi, may I ask if there is any update on this?

**Comment by Googolxx** [comment]
It may take a few days. Sorry for that.

**Comment by Googolxx** [comment]
Sorry for waiting for a long time. I upload the pretrained weights of STF.

**Comment by duanzhiihao** [comment]
Thanks for that! I will try it out and adequately cite your work :)

**Comment by Googolxx** [comment]
I should have uploaded it months ago. Tell me if you got any problems with the checkpoint, I will check it.
