### ISSUE TITLE
the results of executing the pre-training model

### ISSUE THREAD

**Issue by lunalovegood600** [Googolxx/STF#12]
Sorry to disturb you：
 could u please tell me what are the results of executing the pre-training model？Is it only the value of mse  、bpp、psnr ...or something else？ And where can I see the results？So what would be the result of my successful implementation of the pre-training model？
by the way，are u Chinese？Can we communicate in Chinese？HAha。。
I would appreciate any reply。

**Comment by Googolxx** [comment]
可以用中文交流的哈。
测试训练好的模型主要是关注bpp和psnr的RD曲线，比如说同bpp下，psnr越高越好。执行evolution函数（也就是compressai.utils.eval_model）会打印出结果（相应的bpp，psnr，msssim等）。
测试得到的结果能够达到论文中RD曲线的效果（比如说同bpp下，能够达到曲线中对应的psnr值）。这个可以调用python自带的绘图库（类似matplotlib.pyplot）来比较方便的查看。
