### ISSUE TITLE
压缩高分辨率图像

### ISSUE THREAD

**Issue by lunalovegood600** [Googolxx/STF#16]
作者您好，想问下您有没有尝试过用cnn预训练模型去压缩比较大的图像？我下载了您的基于cnn的预训练模型后，压缩了一张3.6M的图像，得到了如下结果：

  "name": "cnn",
  "description": "Inference (ans)",
  "results": {
    "psnr": [
      36.9149467424472
    ],
    "ms-ssim": [
      0.9617322683334351
    ],
    "bpp": [
      0.05067232837933475
    ],
    "encoding_time": [
      0.5175447463989258
    ],
    "decoding_time": [
      0.34578394889831543
    ]
  }
其中单看psnr可能会觉得效果很好，但是bpp为0.05几，这样子的结果是正常的嘛？我又压缩了一张大小为6M左右的图像，得到的结果为："name": "cnn",
  "description": "Inference (ans)",
  "results": {
    "psnr": [
      35.43835283028224
    ],
    "ms-ssim": [
      0.9664726257324219
    ],
    "bpp": [
      0.03681968530415619
    ],
    "encoding_time": [
      1.4469022750854492
    ],
    "decoding_time": [
      0.8462481498718262
    ]
  }
bpp的结果为0.036几，感觉很奇怪。不知道您有没有压缩过比较大的图像，结果是怎样呢？如果能得到回复我将会很感激！！

**Comment by Googolxx** [comment]
压缩单个图像bpp为0.05左右也不是很奇怪的事。
对于你的担忧，我建议你可以在compressai下用其他模型，在接近的码率下也测试下，如果bpp也比较低，说明结果就是正常的。

**Comment by lunalovegood600** [comment]
在compressai下用其他模型是指官方compressAI下的代码模型，例如mbt2018，cheng2020之类的吗？

**Comment by Googolxx** [comment]
是的，compressai有提供预训练模型。

**Comment by lunalovegood600** [comment]
好的谢谢谢！我去试试！

**Comment by xiaqiqi857** [comment]
您好请问一下这个预训练模型是在哪下的呀，谢谢您

> 作者您好，想问下您有没有尝试过用cnn预训练模型去压缩比较大的图像？我下载了您的基于cnn的预训练模型后，压缩了一张3.6M的图像，得到了如下结果：
> 
> "name": "cnn", "description": "Inference (ans)", "results": { "psnr": [ 36.9149467424472 ], "ms-ssim": [ 0.9617322683334351 ], "bpp": [ 0.05067232837933475 ], "encoding_time": [ 0.5175447463989258 ], "decoding_time": [ 0.34578394889831543 ] } 其中单看psnr可能会觉得效果很好，但是bpp为0.05几，这样子的结果是正常的嘛？我又压缩了一张大小为6M左右的图像，得到的结果为："name": "cnn", "description": "Inference (ans)", "results": { "psnr": [ 35.43835283028224 ], "ms-ssim": [ 0.9664726257324219 ], "bpp": [ 0.03681968530415619 ], "encoding_time": [ 1.4469022750854492 ], "decoding_time": [ 0.8462481498718262 ] } bpp的结果为0.036几，感觉很奇怪。不知道您有没有压缩过比较大的图像，结果是怎样呢？如果能得到回复我将会很感激！！
