### ISSUE TITLE
关于compressai平台的问题

### ISSUE THREAD

**Issue by haotiangao** [Googolxx/STF#21]
作者你好，看了你的文章里面的结果对比里有和很多传统方法（JPEG、BPG、VVC等）压缩后的图片比较，我查看compressai的文档里面只能使用这些方法对数据集进行评估，得到bpp，psnr这些性能指标。想问一下可以使用compressai得到这些传统方法压缩后的图片吗？可以的话是怎么实现的呢？十分感谢！

**Comment by Googolxx** [comment]
这是因为compressai并没有对重建图像可视化和保存。这个问题很容易解决，你修改一下compressai的代码，把重建得到的图像像素值保存为图片就ok，加几行代码就能解决。

**Comment by haotiangao** [comment]
好的好的，我去对应的代码部分查看一下，十分感谢！
