### ISSUE TITLE
一些请教

### ISSUE THREAD

**Issue by Jerrry-Li** [Googolxx/STF#25]
![image](https://github.com/Googolxx/STF/assets/94351217/4ee14b25-57df-471b-b13b-1265604acf63)
大神你好，您知道这种图是怎么生成的么，和您论文里的bitmap有些相似

**Comment by Jerrry-Li** [comment]
还有一个问题就是，mean,scale,可以通过加载.tar重建出来吗，.tar里有特征的权重，举个例子：就以您代码里的cc_meantransform来说，有9次transform,每次transform所得到的mean可以通过加载cc_meantransform这个model来得到9个不同的means,不知道我说的对不对，还请您不吝赐教。谢谢大神了🌹🌹

**Comment by Googolxx** [comment]
1.图，类似的逻辑，只是调用的库，以及画图的参数可能有差异。
2.你的意思就是要保存mean,scale的值，然后重建出来？这个你直接定义一个全局变量，保存下来就可以了吧？不知道我理解的对不对。

**Comment by Jerrry-Li** [comment]
好的好的，感谢🙇‍
