### ISSUE TITLE
【Inquiries on Training Issues】

### ISSUE THREAD

**Issue by wonlee2019** [Googolxx/STF#27]
Dear Googolxx,

I am retraining the pytorch implementation, and randomly choose the 150k training images & 50k testing images.

And i follow the training usage "CUDA_VISIBLE_DEVICES=0,1 python train.py -d /path/to/image/dataset/ -e 1000 --batch-size 16 --save --save_path /path/to/save/ -m stf --cuda --lambda 0.0035"

But there exists a problem :: training slowly, four hours per epoch; and "-e 1000" will cost 166 days for one lambda.
 
Further, i use the 4090 GPU, the training status is followed as 
![image](https://github.com/Googolxx/STF/assets/58161731/e2116bff-194c-45d7-b027-fc93b85e3de6)
![image](https://github.com/Googolxx/STF/assets/58161731/24339700-e8c0-4347-9771-928bee2bcd03)
and one training process owns many PIDs (MAYBE this situation causes the slow training speed?)
![image](https://github.com/Googolxx/STF/assets/58161731/2e2b8843-a4c0-4c3d-94da-6fdb7dcd5baf)

Am i miss something or should i consider some tips/tricks ? What steps can be taken to increase training speed？

**Comment by Googolxx** [comment]
See this [issue](https://github.com/Googolxx/STF/issues/3#issuecomment-1094867515) for training details.
Actually, the 'epochs' depends on train set, so using 'iterations' is more appropriate to describe the training details.
It takes about 1.4-1.8 million iterations (140+epochs for your train set) to finish the training. 
On 2080Ti GPU x 2, roughly takes 10-14 days.

**Comment by wonlee2019** [comment]
Thanks a lot!
