### ISSUE TITLE
导入compressai失败

### ISSUE THREAD

**Issue by Joanna-0421** [Googolxx/STF#32]
作者您好，想请问一下，我在import compressai的时候，出现了以下报错：
ModuleNotFoundError: No module named 'compressai._CXX'
我认为可能是只导入了您仓库中改写过的compressai，并没有导入原始compressai仓库，但是我已经使用pip install compressai安装了原始compressai仓库，想问一下这种情况应该怎么解决？

**Comment by vigorouspp** [comment]
您好，我也遇到了相同的问题，请问有解决吗

**Comment by cream-sketch** [comment]
同问

**Comment by Joanna-0421** [comment]
> 您好，我也遇到了相同的问题，请问有解决吗

我认为是因为当当前文件中有compressai时，python会先引用本地的，而不会引用系统安装的库，而这个项目中的compressai文件夹中删掉了之前compressai库中关于这部分的内容。我的解决方案是，将该项目的compressai改一个名字，防止自己代码中引用compressai的时候，引用到这个文件夹中的。

**Comment by Dbvdgd** [comment]
建议CompressAI用官方版本的，把作者仓库模型相关的代码从compressai下面迁移出来，不要和compressai混在一起
