### ISSUE TITLE
Regarding the issue of multi-GPU training

### ISSUE THREAD

**Issue by xuezhongcailian** [Googolxx/STF#34]
Regarding the issue of multi-GPU training, the official 'compressai' is still in the experimental stage for multi-GPU support. Does your model support multi-GPU? When will it support multi-GPU training, and when will it not?

**Comment by HappyTree523** [comment]
> 关于多GPU训练的问题，官方的“compressai”仍处于多GPU支持的实验阶段。您的型号是否支持多 GPU？它什么时候支持多GPU训练，什么时候不支持？

我测试是支持多GPU训练的

**Comment by Googolxx** [comment]
The train scripts support Multi-GPU training, but do not support Multi-GPU acceleration components such as NCCL.
