### ISSUE TITLE
关于数据的问题

### ISSUE THREAD

**Issue by guoguo1314** [Googolxx/STF#8]
您好，请问一下，您Table1的数据是用自己的数据集重新再跑的一遍得出结果吗？还是用的compressai给的结果。那率失真曲线图中的全部数据也是用自己数据集跑的吗？还是用的compressai给的结果？谢谢了！

**Comment by Googolxx** [comment]
table1的数据是我用compressai的预训练模型在同样的GPU上跑的结果。RD 曲线是从对应论文的开源库中取到的数据。

**Comment by likestarsss** [comment]
您好，我想问一下该如何对同一个模型获取到不同的bpp下的psnr，ss-ssim的值。方便加一下吗？我有些问题需要请教下您

**Comment by guoguo1314** [comment]
好的谢谢博主了！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月17日(周一) 中午11:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Googolxx/STF] 关于数据的问题 (Issue #8)




 
您好，我想问一下该如何对同一个模型获取到不同的bpp下的psnr，ss-ssim的值。方便加一下吗？我有些问题需要请教下您
