### ISSUE TITLE
关于如何获取不同bpp下的psnr，ss-ssim

### ISSUE THREAD

**Issue by likestarsss** [Googolxx/STF#9]

**Comment by likestarsss** [comment]
您好，我想问一下该如何对同一个模型获取到不同的bpp下的psnr，ss-ssim的值。方便加一下吗？我有些问题需要请教下您。谢谢了

**Comment by Googolxx** [comment]
获取不同bpp下的psnr和ms-ssim需要调节超参lambda的值。具体的对应代码如下：
https://github.com/Googolxx/STF/blob/0e2480434542af1ac9566e903c57ca0d9d9bf954/train.py#L220-L226
比如针对psnr进行训练的时候，RD曲线的point对应的lambda取值分别是{0.0018, 0.0035, 0.0067,0.0130, 0.025, 0.0483}.

**Comment by likestarsss** [comment]
意味着我需要把每个lambda的参数都训练一遍模型对吧，老哥。谢谢了

**Comment by Googolxx** [comment]
是的

**Comment by likestarsss** [comment]
老哥方便加个联系方式吗，我刚刚接触这方面，可能存在很多问题需要请教您

**Comment by Googolxx** [comment]
你邮件发联系方式吧。zourenjie2020@ia.ac.cn

**Comment by likestarsss** [comment]
好的
